### PR TITLE
[Fix] missing upstream fixes

### PR DESCRIPTION
**Pull request by g5t**

### CODE REVIEW

**Comment by g5t** [comment]
@willend I don't have an easy way to test that I've implemented your changes correctly, especially https://github.com/McStasMcXtrace/McCode/pull/1761

Could you possibly use this branch with your testing infrastructure to check if things look right?
[artifact.zip](https://github.com/user-attachments/files/17800586/artifact.zip)
(The actions derived wheel and source distributions are attached, should you need them)

**Comment by willend** [comment]
@g5t thanks, I have installed locally via the .whl which came in very handy!

Current test incoming is for CPU MPI initially (should I try with --openacc / multicore also?)

**Comment by g5t** [comment]
It's the OPENACC/MULTICORE defines that I'm least confident about, so a test that exercises them would be welcome :grin:

**Comment by willend** [comment]
Since I only had mccode-antlr tooling on the CPU-only box, testing with GPU/OPENACC required a little more handheld configuration....  But now an 8-way GPU run is also incoming.

**Comment by willend** [comment]
@g5t just added a commit to PR home-branch that adds a little define-hierarchy at the top of the cogen header:

```
#ifndef WIN32
#  ifndef OPENACC
#    define _GNU_SOURCE
#  endif
#  define _POSIX_C_SOURCE 200809L
#endif
```

(The `_GNU_SOURCE` **needs** to be there to ensure correct use of `__builtin_isnan` on (also very old libc) gcc-environments like conda, for the Nvidia `nvc` (openacc) compiler, that define **should not** be there, and naturally `cl.exe` understands none of it all ;-) )

With this, most of the differences in compilation success between "CPU-antlr" and "GPU-antlr" seen in https://new-nightly.mcstas.org/2024-11-18_output/2024-11-18_output.html (col 2-3 vs 4) should go away...

**Review by willend — APPROVED** [review]
As mentioned on the PR itself, I just a commit to PR home-branch that adds a little define-hierarchy at the top of the cogen header:

```
#ifndef WIN32
#  ifndef OPENACC
#    define _GNU_SOURCE
#  endif
#  define _POSIX_C_SOURCE 200809L
#endif
```
(The _GNU_SOURCE needs to be there to ensure correct use of __builtin_isnan on (also very old libc) gcc-environments like conda, for the Nvidia nvc (openacc) compiler, that define should not be there, and naturally cl.exe understands none of it all ;-) )

With this, most of the differences in compilation success between "CPU-antlr" and "GPU-antlr" seen in https://new-nightly.mcstas.org/2024-11-18_output/2024-11-18_output.html (col 2-3 vs 4) should go away...

**Pull request merged**
